name: ESGI Todo app

on:
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: ["develop", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Dependencies
        uses: abatilo/actions-poetry@v2.1.3

      - name: Install
        run: |
          python -m pip install --upgrade pip
          poetry config virtualenvs.in-project true
          poetry install

      - name: Tests
        run: |
          source .venv/bin/activate
          poetry --version
          pwd
          ls -la
          pytest tests/api
